default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: highlight_development  #アプリケーション名はご自身のものに変更してください

test:
  <<: *default
  database: highlight_test  #アプリケーション名はご自身のものに変更してください

production:
  <<: *default
  database: highlight_production  #アプリケーション名はご自身のものに変更してください
  username: root            #rootに変更
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock